slownik_mstatusow = {
    "G": {
        "01": "Head Jam/Knife Jam",
        "03": "Black mark error",
        "05": "Paper out",
        "07": "Paper not loaded or paper jam before transport.",
        "08": "Communications error.",
        "09": "Printer open",
        "10": "Ribbon needs to be replaced soon (not thermal printer)",
        "11": "Printhead needs to be replaced soon.",
        "12": "Knife needs to be replaced soon.",
        "13": "Ribbon needs to be replaced now (not thermal printer)",
        "14": "Printhead needs to be replaced now.",
        "15": "Sideways communications error.",
        "16": "Eject jam.",
        "17": "Transport jam.",
        "18": "Capture jam.",
        "19": "Paper not winding.",
        "20": "Mechanism jammed.",
        "21": "No receipt during control.",
        "23": "Capture bin full.",
        "24": "Power supply voltage error.",
        "25": "Control board error.",
        "26": "Head over heated (recoverable). 10s transient status. Not reported.",
        "27": "Head burnt out (non-recoverable).",
        "28": "Paper low.",
        "29": "Exit jam on capture.",
        "30": "Knife needs replaced now.",
        "31": "Receipt transport not connected on power up.",
        "32": "Media not cleared.",
        "34": "Dual feed mechanism jam."
    },
    "D": {
        "01": "Blank track.",
        "03": "Read error.",
        "04": "Write error - write data error.",
        "05": "No card in reader (at stage position) at start of command.",
        "06": "Card removed by customer during capture.",
        "07": "Shutter jammed open after card staged.",
        "08": "Shutter switch failure detected.",
        "09": "Error recovery successful - invalid card ejected.",
        "10": "Shutter jammed closed on entry or eject.",
        "11": "Card jam - or - invalid card in throat at startup.",
        "12": "Card captured after unsuccessful eject.",
        "13": "Possible customer tampering - card jammed in throat, unable to pull card into reader.",
        "14": "Too many consecutive read errors or blank tracks on any track.",
        "15": "Too many consecutive write errors.",
        "16": "Too many consecutive card jams.",
        "17": "Too many consecutive shutter jammed closed (not shutter test).",
        "18": "Card jam during capture - unsuccessful eject.",
        "19": "Too many consecutive invalid cards.",
        "20": "Device still inoperative (not diagnostics)."
    },
    "L": {
        "01": "Parity error.",
        "02": "Wykryto błąd sprzętowy podczas transmisji klucza lub danych albo podczas operacji szyfrowania.",
        "03": "Nieprawidłowe polecenie, nie wszystkie przestrzenie klawiszy są zamknięte.",
        "04": "Nieprawidłowe polecenie, brak otwartej przestrzeni klawiszy.",
        "05": "Nieprawidłowe polecenie, ponieważ klawiatura jest obecnie włączona.",
        "07": "Błąd komunikacji.",
        "08": "Reset modułu bezpieczeństwa powiódł się.",
        "11": "Nieprawidłowe dane polecenia.",
        "12": "Niezgodność danych/błędne dane.",
        "13": "Nie załadowano klucza umożliwiającego żądanie operacji szyfrowania lub deszyfrowania.",
        "38": "Invalid key, key does not exist.",
        "50": "Invalid parameter field.",
        "65": "Invalid password, no match.",
        "70": "PIN verification failed.",
    },
    "E": {
        "01": "Dispense requested from a cassette which is not installed or no cassettes installed during self test",
        "02": "Too many bills being rejected",
        "03": "Pick failure.",
        "04": "Pick failure plus low (Out of bills).",
        "05": "Wystąpiła awaria czujnika lub zator gotówki w transporcie głównym lub dokonano krótkiego wydania (rachunki wydano mniej niż żądano) i nie zgłoszono żadnego błędu.",
        "06": "Divert gate fault (spray type dispenser)...",
        "07": "Purge bin (zrzutówka) not present (unit inoperative).",
        "08": "Purge bin full (zrzutówka) (unit inoperative).",
        "09": "Communications failure (USB S1 Dispenser)...",
        "10": "Operation not attempted due to fatal device/cassette error.",
        "11": "Bills still stacked in transport / previous error not cleared...",
        "12": "Presenter clamping mechanism jammed.",
        "13": "Exit shutter is jammed open.",
        "14": "Exit shutter is jammed closed.",
        "16": "Główny dysk rozrządu transportu nie działa prawidłowo lub główny silnik prądu przemiennego uległ awarii.",
        "18": "Currency jam in presenter or transport sensor failure.",
        "19": "Exit sensor blocked after present.",
        "28": "NVRAM access error (SOH update failed).",
        "29": "Dysk taktowania transportu prezentera nie działał prawidłowo lub silnik uległ awarii.",
        "30": "Jeden z czujników transportu prezentera uległ awarii lub został zablokowany.",
        "32": "Heartbeat on execution processor failed.",
        "33": "Awaria komunikacji na magistrali 12C procesora wykonawczego.",
        "34": "A present bills operation has been attempted withous any bills being stacked or a RETRACT with no bills presented.",
        "35": "Operacja niekompletna z powodu odłączenia zasilania AC i 24V DC przez blokadę na drzwiach dostępu do bankomatu.",
        "36": "ANie przeprowadzono testu zaworu wybierającego, ponieważ zainstalowano kasety.",
        "37": "Usługa wskaźnika sabotażu jest włączona.",
        "38": "Usługa wskaźnika sabotażu jest wyłączona.",
        "39": "LVDT/NTS lub powiązany obwód działa nieprawidłowo.",
        "40": "Parametry rachunku nie zostały skonfigurowane. Dzieje się tak, ponieważ jest to pierwsza operacja od pierwszego włączenia zasilania lub wystąpiło uszkodzenie pamięci NVRAM i pamięć NVRAM została ponownie zainicjowana.",
        "41": "An attempt to pick from a cassette in a pick module which has been disabled for in-service replenishment.",
        "42": "The dispenser has not been authenticated by the PC Core module. This code is only generated by USB S1 dispenser variants..",
        
    },
    "Iw": {
        "03": "Pick failure",
        "05": "Sensor failure or currency jam in main transport or A short dispense was performed (bills dispensed fewer tha bills requested) and no error was reported.",
        "10": "Operation not attempted because of fatal device/cassette error.",
        "13": "Exit shutter is jammed open",
        "25": "Interlock open",
        "30": "Media jam at Centraliser",
        "31": "Media jam between feed and BV",
        "33": "Media jam beetween BV and ESCROW",
        "35": "ESCROW media jam",
        "39": "Media jam in upper exeption cassette path",
        "42": "Media jam at intermedia transport",
        "43": "Lower transport error.",
        "50": "There has been a mechanism failure in the dispenser while attempting to execute a request. Mechanism Fault - Pick 6",
        "95": "Magnetic sensor fault",
    }
}